name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/cosmotherapy2008/cosmotalks-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cosmotalks-backend \
            --image gcr.io/cosmotherapy2008/cosmotalks-backend \
            --platform managed \
            --region europe-west4 \
            --project cosmotherapy2008 \
            --set-env-vars="COOKIE_KEY=${{ secrets.COOKIE_KEY }},GCP_SA_KEY=${{ secrets.GCP_SA_KEY }},GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},MONGO_URI=${{ secrets.MONGO_URI }},GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}"